config/routes.rb
DevconApp::Application.routes.draw do
  get "pages/home"
  get "forecastrequests/new"
  
  resources :forecastrequests
  
  match '/forecast', :to => 'forecastrequests#new'
  match '/', :to => 'pages#home'
  root :to => 'pages#home'
  
end

app/models/forecastrequest.rb
# == Schema Information
#
# Table name: forecastrequests
#
#  id         :integer         not null, primary key
#  email      :string(255)
#  startdate  :datetime
#  enddate    :datetime
#  interval   :integer
#  data       :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require "uri"
require "net/http"
require 'nokogiri'

class Forecastrequest < ActiveRecord::Base

  PE_URL = 'http://testcloud.injixo.com/PredictionEngine/PredictionEngine.svc/'

  attr_accessible :email, :startdate, :enddate, :interval, :data, :result
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  
  validates :email, :presence => true,
				    :format => { :with => email_regex } #,:uniqueness => { :case_sensitive => false }
            
  validates :startdate, :presence => true
  
  validates :enddate, :presence => true
           
  validates :interval, :presence => true
  
  validates :data, :presence => true
  
  
  def make_hash
    return nil if !(self.data) 
	mydata = self.data.gsub("\r","").gsub("\t",",")
	dataarray = mydata.split("\n")
    datahash = {}
    dataarray.each do |workload|
      wl = workload.split(',')
      datahash[wl[0]] = wl[1]
    end
    return { :startdate  => self.startdate.strftime("%Y-%m-%dT%H:%M:%SZ"),
             :enddate    => self.enddate.strftime("%Y-%m-%dT%H:%M:%SZ"),
             :interval   => self.interval.to_s,
             :wlc        => datahash }
  end
 
  

  def computeforecast
    res = getforecast
    if res == nil
      self.result = "Invalid input!"
#    elsif res == Net::HTTPSuccess
	else
	  self.result = Forecastrequest.hash_to_csv(Forecastrequest.xml_to_hash(res.body))
     # self.result += res.body if !self.result
    end
  end
 

  def getforecast
    hash = make_hash
	if hash != nil
	  url = URI.parse(PE_URL)
      request = Net::HTTP::Post.new(url.path)
      request['Accept'] = "text/xml"
      request['Content-Type'] = "text/xml"
	  request.body = self.inputcreator(hash)
	  res = Net::HTTP.start(url.host, url.port) { |http|
      http.request(request)
      }
	  #puts "OUTPUT"
      #puts res.body
	  return res
	end
	return nil
  end 		#def

  

  def self.xml_to_hash(xml)
    return nil if !xml
	hash ={} 
    doc = Nokogiri::XML(xml)
    doc.remove_namespaces!
	doc.xpath('//wl').each do |wl|
      hash["#{wl.attribute('ts')}"] = "#{wl.content}"
    end
    return hash
  end

  def self.hash_to_csv(hash)
    return nil if !hash
	csv = ""

    hash.keys.sort{|x,y| x <=> y}.each do |key| 
      csv << "#{key},#{hash[key]}\n"
    end
    return csv
  end
  
  
  def getDailyValues(csv)
    return [] unless self && csv
	timeframe = ((self.enddate - self.startdate) / 86400).to_i
	timeframe = 100 if timeframe > 100
	daily = Array.new(timeframe)
	csv.split("\n").each {|l|
	  ks,v = l.split(",")
	  k = Time.zone.parse(ks)
	  d = ((k - self.startdate) / 86400).to_i
	  if d <= timeframe
	    daily[d] = !daily[d] ? v.to_i : daily[d] + v.to_i
	  end
	}
	
    return daily

  end


  def inputcreator(hash)
    @input = "<?xml version=\"1.0\" encoding=\"utf-8\"?><ForecastRequest xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns=\"PredictionEngine\" xmlns:version=\"1.0\">"
    #startdate
	@input = @input + "<startdate>" + hash[:startdate] + "</startdate>"
	#enddate:
	@input = @input + "<enddate>" + hash[:enddate] + "</enddate>"
	#interval of historical- and forecast data:
	@input = @input + "<forecastinterval>" + hash[:interval].to_s + "</forecastinterval> <historicalinterval>" + hash[:interval].to_s + "</historicalinterval>"
    #workloadcollection:
	@input = @input + "<wlc>"
	
	hash[:wlc].each do |key, value|
      @input = @input + "<wl ts =\"" + key + "\">" + value + "</wl>"
	end
	@input = @input + "</wlc> </ForecastRequest>"
	return @input
  end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end


#devcon

app/controllers/forecastrequests_controller.rb
class ForecastrequestsController < ApplicationController
  
  def new
    @forecastrequest = Forecastrequest.new
    render 'new'
  end
  
	
  def create
	@forecastrequest = Forecastrequest.new(params[:forecastrequest])
	@forecastrequest.save!
    @forecastrequest.computeforecast
	@forecastrequest.save!
	render 'show'
  end
  
  

  def destroy
    @forecastrequest = Forecastrequest.find(params[:id])
    @forecastrequest.destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecastrequests_helper.rb
module ForecastrequestsHelper

def add_datepicker(name)
    img = image_tag('datepickerpopup.gif', :alt => "DatePicker")
	link_to img, "#", :onclick => "displayDatePicker('forecastrequest[#{name}]',this,'ymd','-');"
end#def

def injixo_logo
    img = image_tag('injixo.jpg')
	link_to img, "http://www.injixo.com"
end#def

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/forecastrequests/_form.html.erb
<%= form_for(@forecastrequest) do |f| %>
  <% if @forecastrequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forecastrequest.errors.count, "error") %> prohibited this forecastrequest from being saved:</h2>

      <ul>
      <% @forecastrequest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.datetime_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :interval %><br />
    <%= f.text_field :interval %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forecastrequests/_showinpdata.html.erb
<p>
  <b>Historical data:</b><br />
  <textarea class="inputdata" rows=15 cols=27 readonly><%= @forecastrequest.data.gsub(":00Z,","\t") %></textarea>
  
</p>
 

app/views/forecastrequests/_showinput.html.erb
<p>
  <b>Email:</b><br/>
  <input type="text" value="<%=@forecastrequest.email%>" readonly/> 
</p>

<p>
  <b>Time range:</b><br/>
  <input type="text" value="<%=@forecastrequest.startdate%>" size=10 readonly/> <img src='images/datepickerpopup.gif'/>
  <input type="text" value="<%=@forecastrequest.enddate%>" size=10 readonly/> <img src='images/datepickerpopup.gif'/>
</p>


<p>
  <b>Interval:</b><br />
  <input type="radio" <%= "checked" if (@forecastrequest.interval == 15) %> disabled /> 15 Minutes<br />
  <input type="radio" <%= "checked" if (@forecastrequest.interval == 30) %> disabled /> 30 Minutes<br />
  <input type="radio" <%= "checked" if (@forecastrequest.interval == 60) %> disabled /> 60 Minutes<br />
</p>

app/views/forecastrequests/_showoutputdata.html.erb
   <script type="text/javascript">
    /* <![CDATA[ */
    $(function() {
        /* This code runs when everything has been loaded on the page */
        /* Inline sparklines take their values from the contents of the tag */

		 // Customized line chart
        $('.linecustom').sparkline('html', {height: '100px', width: '250px', minSpotColor: false, maxSpotColor: false, spotColor: '#77f', spotRadius: 3});
		
    });
    /* ]]> */
    </script>

<p>
  <b>Result:</b><br />
  <textarea rows=15 cols=32><%=@forecastrequest.result %></textarea><br />
  <a href="mailto:<%=@forecastrequest.email%>?subject='Forecast created from <%=@forecastrequest.startdate%> to <%=@forecastrequest.enddate%>'&body='Forecast is available at ID <%=@forecastrequest.id%>'">Send to email address</a>
  </p>

  <b>Result graph (Daily sums):</b><br />
 <div class="linecustom"><%= @forecastrequest.getDailyValues(@forecastrequest.result).join(",") %></div>

app/views/forecastrequests/edit.html.erb
<h1>Editing forecastrequest</h1>

<%= render 'form' %>

<%= link_to 'Show', @forecastrequest %> |
<%= link_to 'Back', forecastrequests_path %>

app/views/forecastrequests/index.html.erb
<h1>Listing forecastrequests</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <th>Interval</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

</table>

<br />

<%= link_to 'New Forecastrequest', new_forecastrequest_path %>

app/views/forecastrequests/new.html.erb
<script type="text/javascript" src="../javascripts/datepicker.js"> </script>
<h1><%= injixo_logo %>Forecast request - create</h1>

<%= form_for @forecastrequest,  :multipart => true  do |f| %>

<table class="results">
<tr>
<td class = "round dataarea" width=350>
  <div class="field">
    <b>Email:</b><br />
    <%= f.text_field :email %>
	</div>
  <div class="field">
    <b>Time range:</b><br />
	<%= f.text_field :startdate, :size => 10 %>
	<%= add_datepicker("startdate") %>
    <%= f.text_field :enddate , :size => 10 %>
	<%= add_datepicker("enddate") %>
  </div>

  <div class="field">
    <b>Interval:</b><br />
    <%= f.radio_button :interval, "15"  %>15 Minutes<br/>
    <%= f.radio_button :interval, "30"  %>30 Minutes<br/>
    <%= f.radio_button :interval, "60"  %>60 Minutes<br/>
  </div>
</td>
  <td class = "round dataarea"width=350>
    <div class="field">
      <b>Historical data:</b><br />
      <%= f.text_area :data %>
    </div>

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  </td>
  <td class = "round dataarea" width=350>
    <b>Result:</b><br />
	Press submit to send the historical data to the Prediction Engine. 
	The PE will generate a forecast based on the given data and return this data.
  </td>
</table>
  
<% end %>

<%= link_to 'Back', root_path %>

app/views/forecastrequests/show.html.erb
<h1><%= injixo_logo %>Forecast request - result</h1>
<p id="notice"><%= notice %></p>

<table class="results">
<tr>
<td class = "round dataarea" width=350>
  <%= render 'showinput' %>
</td>
<td class = "round dataarea" width=350>
  <%= render 'showinpdata' %>
</td>
<td class = "round dataarea" width=350>
  <%= render 'showoutputdata' %>
</td>
</tr>
</table>

<%= link_to 'Back', forecastrequests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevCon App</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <script type="text/javascript" src="/javascripts/jquery-1.7.1.js"></script>
  <script type="text/javascript" src="/javascripts/jquery.sparkline.js"></script>  
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
  <section class="round">

<%= yield %>
</section>
</div>
      <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/home.html.erb
<h1><%= injixo_logo %>DevCon App - Home</h1>
<p>Click here to upload data and generate a forecast for this data. You only have to enter your mail address, give the start and end date of the forecasting time frame and the data interval and then you'll have to copy the data form Excel or CSV to the webpage. On submitting the data the Prediction Engine will get involved to calculate the patterns, trends and peaks in the given data to provide the result.</p>
<br />
<br />
<%= link_to "Request Forecast", forecast_path, :class => "reqforecast_button round" %>